# DuckDB 财务筛选工作流 (v2.0)
# ========================================
#
# 更新日志 (2025-12-06):
# - 新增 reference_metrics 交叉验证配置
# - 支持 MetricAdapter 自动调整分析参数
# - 29条规则引擎 (7 veto + 10 penalty + 6 cross-val + 3 cycle + 5 bonus)
# - 5种策略评估 (high_growth, turnaround, stable_dividend, cyclical_bottom, moat_defense)
#
# 指标配置说明:
# - roic: 效率指标，核心筛选指标，交叉验证 roe/roiic
# - roiic: 增量指标，辅助指标（不做一票否决），交叉验证 roic
# - total_revenue_ps: 规模指标，验证增长可持续性，交叉验证 roe
# - eps: 规模指标，盈利增长，交叉验证 ocfps（现金含金量）
# - grossprofit_margin: 效率指标，护城河指标，交叉验证 netprofit_margin
# - netprofit_margin: 效率指标，盈利能力
# - roe: 效率指标，股东回报，杜邦分解验证
# - ocfps: 现金流指标，盈利质量验证
#
pipeline:
  name: "DuckDB财务基线筛选管道"
  orchestration:
    granularity: node
    soft_fail: true
    task_runner: "sequential"
    max_workers: 4
    retry_count: 1
    retry_delay: 10
    timeout: 1200

  steps:
    - name: "Load_Financial_Data"
      component: "business_engine"
      engine: "duckdb"
      method: ["load_file"]
      parameters:
        path: "data/polars/5yd_final_industry.csv"
      outputs:
        parameters:
          - name: Raw_Data

    # ========== ROIC 趋势分析(三位一体过滤) ==========
    # 核心指标：投入资本回报率，衡量资本效率
    # 交叉验证：ROE（股东视角）、ROIIC（增量效率）
    - name: "Analyze_ROIC_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'roic'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["roe", "roiic"]  # 新增交叉验证
      outputs:
        parameters:
          - name: ROIC_Trend_Result

    - name: "Score_ROIC_Quality"
      component: "business_engine"
      engine: "scoring"
      method: ["score_quality"]
      parameters:
        data: "steps.Analyze_ROIC_Trend.outputs.parameters.ROIC_Trend_Result"
        report_path: "data/filter_middle/roic_quality_report.txt"
      outputs:
        parameters:
          - name: ROIC_Quality_Result

    - name: "store_ROIC_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/roic_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_ROIC_Trend.outputs.parameters.ROIC_Trend_Result"

    - name: "store_ROIC_Quality"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/roic_quality_scored.csv"
        format: "csv"
        data: "steps.Score_ROIC_Quality.outputs.parameters.ROIC_Quality_Result"

    # ========== ROIIC 趋势分析 (增量资本回报) ==========
    # 辅助指标：增量资本回报率，评估新投资效率
    # 特殊处理：不做一票否决，降低扣分权重
    # 交叉验证：ROIC（存量效率）
    - name: "Analyze_ROIIC_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'roiic'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["roic"]  # 新增交叉验证
      outputs:
        parameters:
          - name: ROIIC_Trend_Result

    - name: "store_ROIIC_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/roiic_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_ROIIC_Trend.outputs.parameters.ROIIC_Trend_Result"

    # ========== 营收趋势分析 (规模增长) ==========
    # 交叉验证：ROE（增长效率）+ EPS（增收是否增利）
    - name: "Analyze_Revenue_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'total_revenue_ps'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["roe", "eps"]
      outputs:
        parameters:
          - name: Revenue_Trend_Result

    - name: "store_Revenue_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/revenue_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_Revenue_Trend.outputs.parameters.Revenue_Trend_Result"

    # ========== 净利润趋势分析 (盈利增长) ==========
    - name: "Analyze_Profit_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'eps'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["ocfps"]
      outputs:
        parameters:
          - name: Profit_Trend_Result

    - name: "store_Profit_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/profit_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_Profit_Trend.outputs.parameters.Profit_Trend_Result"

    # ========== 毛利率趋势分析 (护城河) ==========
    # 效率指标：毛利率，衡量产品竞争力和议价能力
    # 交叉验证：净利率（费用控制）
    - name: "Analyze_GrossMargin_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'grossprofit_margin'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["netprofit_margin"]  # 新增交叉验证
      outputs:
        parameters:
          - name: GrossMargin_Trend_Result

    - name: "store_GrossMargin_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/gross_margin_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_GrossMargin_Trend.outputs.parameters.GrossMargin_Trend_Result"

    # ========== 净利率趋势分析 (盈利能力) ==========
    # 效率指标：净利率，综合盈利能力
    # 交叉验证：毛利率（成本结构）、现金流（盈利质量）
    - name: "Analyze_NetMargin_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'netprofit_margin'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["grossprofit_margin", "ocfps"]  # 新增交叉验证
      outputs:
        parameters:
          - name: NetMargin_Trend_Result

    - name: "store_NetMargin_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/net_margin_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_NetMargin_Trend.outputs.parameters.NetMargin_Trend_Result"

    # ========== ROE 趋势分析 (股东回报) ==========
    # 效率指标：ROE，股东权益回报率
    # 杜邦分解验证：净利率、ROIC（排除杠杆驱动的虚假高ROE）
    - name: "Analyze_ROE_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'roe'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["netprofit_margin", "roic"]  # 杜邦分解验证
      outputs:
        parameters:
          - name: ROE_Trend_Result

    - name: "store_ROE_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/roe_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_ROE_Trend.outputs.parameters.ROE_Trend_Result"

    # ========== 经营现金流趋势分析 (含金量) ==========
    # 现金流指标：OCF，验证盈利的现金含量
    # 交叉验证：EPS（利润现金比）
    - name: "Analyze_OCF_Trend"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_metric_trend"]
      parameters:
        data: "steps.Load_Financial_Data.outputs.parameters.Raw_Data"
        group_cols: 'ts_code'
        metric_name: 'ocfps'
        prefix: ""
        suffix: ""
        min_periods: 5
        reference_metrics: ["eps"]  # 现金流与利润交叉验证
      outputs:
        parameters:
          - name: OCF_Trend_Result

    - name: "store_OCF_Trend"
      component: "data_engine"
      engine: "polars"
      method:
        - "store"
      parameters:
        file_path: "data/filter_middle/ocf_trend_analysis.csv"
        format: "csv"
        data: "steps.Analyze_OCF_Trend.outputs.parameters.OCF_Trend_Result"

    # ========== 综合报告生成 (Cross-Analysis Report) ==========
    # 依赖所有 store 步骤完成后才执行
    - name: "Generate_Comprehensive_Report"
      component: "business_engine"
      engine: "reporting"
      method: ["report_comprehensive"]
      parameters:
        data_dir: "data/filter_middle"
        output_path: "data/comprehensive_analysis_report.md"
      depends_on:
        - "store_ROIC_Trend"
        - "store_ROIIC_Trend"
        - "store_Revenue_Trend"
        - "store_Profit_Trend"
        - "store_GrossMargin_Trend"
        - "store_NetMargin_Trend"
        - "store_ROE_Trend"
        - "store_OCF_Trend"
        - "store_ROIC_Quality"
      outputs:
        parameters:
          - name: Comprehensive_Report_Path