pipeline:
  name: "Generic Architecture Demo"
  orchestration:
    granularity: node
    soft_fail: true
    task_runner: "sequential"

  steps:
    - name: "Load_Data"
      component: "business_engine"
      engine: "duckdb"
      method: ["load_file"]
      parameters:
        path: "data/polars/5yd_final_industry.csv"
      outputs:
        parameters:
          - name: Raw_Data

    # 1. Generic Analysis (ROIC)
    - name: "Analyze_ROIC_Generic"
      component: "business_engine"
      engine: "duckdb"
      method: ["analyze_generic"]
      parameters:
        data: "steps.Load_Data.outputs.parameters.Raw_Data"
        config:
          group_cols: 'ts_code'
          metric_name: 'roic'
          min_periods: 5
      outputs:
        parameters:
          - name: ROIC_Analysis_Result

    # 2. Generic Scoring
    - name: "Score_ROIC_Generic"
      component: "business_engine"
      engine: "scoring"
      method: ["score_generic"]
      parameters:
        result: "steps.Analyze_ROIC_Generic.outputs.parameters.ROIC_Analysis_Result"
        config:
          weights:
            value: 40
            trend: 40
            momentum: 10
            stability: 10
      outputs:
        parameters:
          - name: ROIC_Score_Result

    # 3. Generic Reporting
    - name: "Report_ROIC_Generic"
      component: "business_engine"
      engine: "reporting"
      method: ["report_generic"]
      parameters:
        result: "steps.Score_ROIC_Generic.outputs.parameters.ROIC_Score_Result"
        output_path: "data/filter_middle/generic_roic_report.txt"
      outputs:
        parameters:
          - name: ROIC_Report_Text

    # 4. Store Scored Data
    - name: "Store_Scored_Data"
      component: "data_engine"
      engine: "polars"
      method: ["store"]
      parameters:
        file_path: "data/filter_middle/generic_roic_scored.csv"
        format: "csv"
        data: "steps.Score_ROIC_Generic.outputs.parameters.ROIC_Score_Result"
