"""ROIIC 行业差异化配置。"""

from __future__ import annotations

from typing import Dict

ROIIC_INDUSTRY_FILTER_CONFIGS: Dict[str, Dict[str, float]] = {
    # ========== 第一类：轻资产/高 ROIIC 行业 ==========
    '软件服务': {
        'min_latest_value': 18.0,
        'excellent_roiic': 30.0,
        'log_severe_decline_slope': -0.25,
        'log_mild_decline_slope': -0.12,
        'trend_significance': 0.5,
        'allow_negative': False,
        'roiic_positive_bonus_threshold': 30.0,
        'roiic_veto_weighted_threshold': 0.0,
        'roiic_veto_latest_threshold': 0.0,
        'wacc_benchmark': 10.0,
        'interpretation': {
            '>30%': '卓越：资本极高效，轻资产扩张',
            '18-30%': '优秀：新增投资回报强劲',
            '12-18%': '良好：略高于资本成本',
            '8-12%': '及格：刚好覆盖资本成本',
            '<8%': '警戒：扩张可能毁灭价值',
            '<0%': '危险：每投入1元亏损，停止扩张',
        },
    },
    '半导体': {
        'min_latest_value': 12.0,
        'excellent_roiic': 20.0,
        'log_severe_decline_slope': -0.30,
        'log_mild_decline_slope': -0.15,
        'trend_significance': 0.45,
        'allow_negative': True,
        'negative_tolerance_years': 2,
        'roiic_positive_bonus_threshold': 20.0,
        'roiic_veto_weighted_threshold': -5.0,
        'roiic_veto_latest_threshold': -5.0,
        'wacc_benchmark': 11.0,
        'interpretation': {
            '>20%': '卓越：技术领先，产能爬坡快',
            '12-20%': '优秀：扩产效率高',
            '8-12%': '良好：扩产有价值',
            '0-8%': '及格：需关注产能利用率',
            '<0%': '警戒：扩产期亏损，验证产能规划',
        },
    },
    '元器件': {
        'min_latest_value': 12.0,
        'excellent_roiic': 20.0,
        'log_severe_decline_slope': -0.30,
        'log_mild_decline_slope': -0.15,
        'trend_significance': 0.45,
        'allow_negative': True,
        'negative_tolerance_years': 2,
        'roiic_positive_bonus_threshold': 20.0,
        'roiic_veto_weighted_threshold': -5.0,
        'roiic_veto_latest_threshold': -5.0,
        'wacc_benchmark': 11.0,
    },
    '生物制药': {
        'min_latest_value': 15.0,
        'excellent_roiic': 25.0,
        'log_severe_decline_slope': -0.28,
        'log_mild_decline_slope': -0.15,
        'trend_significance': 0.5,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 25.0,
        'roiic_veto_weighted_threshold': -3.0,
        'roiic_veto_latest_threshold': -3.0,
        'wacc_benchmark': 10.0,
        'interpretation': {
            '>25%': '卓越：重磅新药成功',
            '15-25%': '优秀：新药管线价值高',
            '8-15%': '良好：R&D 效率可接受',
            '<8%': '警戒：R&D 投入产出比低',
            '<0%': '需验证：可能处于新药研发期',
        },
    },
    '白酒': {
        'min_latest_value': 20.0,
        'excellent_roiic': 35.0,
        'log_severe_decline_slope': -0.20,
        'log_mild_decline_slope': -0.10,
        'trend_significance': 0.6,
        'allow_negative': False,
        'roiic_positive_bonus_threshold': 35.0,
        'roiic_veto_weighted_threshold': 0.0,
        'roiic_veto_latest_threshold': 0.0,
        'wacc_benchmark': 9.0,
        'interpretation': {
            '>35%': '卓越：品牌溢价极强',
            '20-35%': '优秀：扩产+提价双驱动',
            '12-20%': '良好：扩产有效',
            '<12%': '警戒：可能产能过剩或渠道问题',
        },
    },
    # ========== 第二类：中等资产/中 ROIIC 行业 ==========
    '汽车零部件': {
        'min_latest_value': 10.0,
        'excellent_roiic': 18.0,
        'log_severe_decline_slope': -0.35,
        'log_mild_decline_slope': -0.18,
        'trend_significance': 0.45,
        'allow_negative': True,
        'negative_tolerance_years': 2,
        'roiic_positive_bonus_threshold': 18.0,
        'roiic_veto_weighted_threshold': -5.0,
        'roiic_veto_latest_threshold': -5.0,
        'wacc_benchmark': 10.0,
        'interpretation': {
            '>18%': '卓越：配套新能源/高端车',
            '10-18%': '优秀：客户结构优质',
            '5-10%': '及格：传统燃油车配套',
            '<5%': '警戒：客户集中度或技术落后',
            '<0%': '危险：扩产失败或订单流失',
        },
    },
    '机械设备': {
        'min_latest_value': 10.0,
        'excellent_roiic': 18.0,
        'log_severe_decline_slope': -0.35,
        'log_mild_decline_slope': -0.18,
        'trend_significance': 0.4,
        'allow_negative': True,
        'negative_tolerance_years': 2,
        'roiic_positive_bonus_threshold': 18.0,
        'roiic_veto_weighted_threshold': -5.0,
        'roiic_veto_latest_threshold': -5.0,
        'wacc_benchmark': 10.0,
    },
    '化工': {
        'min_latest_value': 8.0,
        'excellent_roiic': 15.0,
        'log_severe_decline_slope': -0.40,
        'log_mild_decline_slope': -0.22,
        'trend_significance': 0.35,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 15.0,
        'roiic_veto_weighted_threshold': -6.0,
        'roiic_veto_latest_threshold': -6.0,
        'wacc_benchmark': 10.0,
        'interpretation': {
            '>15%': '卓越：精细化工/新材料',
            '8-15%': '优秀：产品竞争力强',
            '3-8%': '及格：大宗化工',
            '<3%': '警戒：产能过剩或价格战',
            '<0%': '危险：新建产能亏损',
        },
    },
    # ========== 第三类：周期性/ROIIC 波动大行业 ==========
    '小金属': {
        'min_latest_value': 5.0,
        'excellent_roiic': 25.0,
        'log_severe_decline_slope': -0.50,
        'log_mild_decline_slope': -0.30,
        'trend_significance': 0.25,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 25.0,
        'roiic_veto_weighted_threshold': -8.0,
        'roiic_veto_latest_threshold': -8.0,
        'wacc_benchmark': 12.0,
        'cyclical_adjustment': True,
        'interpretation': {
            '>25%': '景气顶部：谨慎扩产风险',
            '10-25%': '景气期：扩产窗口',
            '5-10%': '平衡期：维持现有产能',
            '0-5%': '底部：等待周期反转',
            '<0%': '萧条期：停止扩产，验证是否产能过剩',
        },
    },
    '钢铁': {
        'min_latest_value': 3.0,
        'excellent_roiic': 15.0,
        'log_severe_decline_slope': -0.60,
        'log_mild_decline_slope': -0.35,
        'trend_significance': 0.25,
        'allow_negative': True,
        'negative_tolerance_years': 4,
        'roiic_positive_bonus_threshold': 15.0,
        'roiic_veto_weighted_threshold': -10.0,
        'roiic_veto_latest_threshold': -10.0,
        'wacc_benchmark': 11.0,
        'cyclical_adjustment': True,
        'interpretation': {
            '>15%': '景气顶部：警惕周期反转',
            '8-15%': '景气期：有限扩产',
            '3-8%': '平衡期：维持',
            '<3%': '底部：停止扩产',
            '<0%': '萧条：验证是否永久产能过剩',
        },
    },
    '有色金属': {
        'min_latest_value': 5.0,
        'excellent_roiic': 20.0,
        'log_severe_decline_slope': -0.50,
        'log_mild_decline_slope': -0.30,
        'trend_significance': 0.25,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 20.0,
        'roiic_veto_weighted_threshold': -8.0,
        'roiic_veto_latest_threshold': -8.0,
        'wacc_benchmark': 11.0,
        'cyclical_adjustment': True,
    },
    '煤炭': {
        'min_latest_value': 5.0,
        'excellent_roiic': 20.0,
        'log_severe_decline_slope': -0.65,
        'log_mild_decline_slope': -0.40,
        'trend_significance': 0.2,
        'allow_negative': True,
        'negative_tolerance_years': 4,
        'roiic_positive_bonus_threshold': 20.0,
        'roiic_veto_weighted_threshold': -10.0,
        'roiic_veto_latest_threshold': -10.0,
        'wacc_benchmark': 11.0,
        'cyclical_adjustment': True,
    },
    # ========== 第四类：重资产/低 ROIIC 行业 ==========
    '房地产': {
        'min_latest_value': 2.0,
        'excellent_roiic': 10.0,
        'log_severe_decline_slope': -0.70,
        'log_mild_decline_slope': -0.45,
        'trend_significance': 0.3,
        'allow_negative': True,
        'negative_tolerance_years': 5,
        'roiic_positive_bonus_threshold': 10.0,
        'roiic_veto_weighted_threshold': -10.0,
        'roiic_veto_latest_threshold': -10.0,
        'wacc_benchmark': 10.0,
        'interpretation': {
            '>10%': '优秀：一二线城市+高周转',
            '5-10%': '良好：正常开发利润',
            '2-5%': '及格：勉强覆盖成本',
            '0-2%': '警戒：土地成本过高',
            '<0%': '危险：库存积压或烂尾风险',
        },
    },
    '建筑装饰': {
        'min_latest_value': 3.0,
        'excellent_roiic': 12.0,
        'log_severe_decline_slope': -0.60,
        'log_mild_decline_slope': -0.35,
        'trend_significance': 0.35,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 12.0,
        'roiic_veto_weighted_threshold': -7.0,
        'roiic_veto_latest_threshold': -7.0,
        'wacc_benchmark': 10.0,
    },
    '建筑材料': {
        'min_latest_value': 5.0,
        'excellent_roiic': 15.0,
        'log_severe_decline_slope': -0.50,
        'log_mild_decline_slope': -0.30,
        'trend_significance': 0.4,
        'allow_negative': True,
        'negative_tolerance_years': 3,
        'roiic_positive_bonus_threshold': 15.0,
        'roiic_veto_weighted_threshold': -8.0,
        'roiic_veto_latest_threshold': -8.0,
        'wacc_benchmark': 10.0,
    },
    # ========== 第五类：特殊行业 ==========
    '新型电力': {
        'min_latest_value': 4.0,
        'excellent_roiic': 12.0,
        'log_severe_decline_slope': -0.50,
        'log_mild_decline_slope': -0.28,
        'trend_significance': 0.35,
        'allow_negative': True,
        'negative_tolerance_years': 5,
        'roiic_positive_bonus_threshold': 12.0,
        'roiic_veto_weighted_threshold': -8.0,
        'roiic_veto_latest_threshold': -8.0,
        'wacc_benchmark': 9.0,
        'interpretation': {
            '>12%': '优秀：光伏/风电效率高',
            '8-12%': '良好：正常发电收益',
            '4-8%': '及格：政策补贴下可行',
            '<4%': '警戒：补贴退坡后难覆盖成本',
            '<0%': '危险：电站选址或技术问题',
        },
    },
}


DEFAULT_ROIIC_FILTER_CONFIG: Dict[str, float] = {
    'min_latest_value': 8.0,
    'excellent_roiic': 18.0,
    'log_severe_decline_slope': -0.40,
    'log_mild_decline_slope': -0.22,
    'trend_significance': 0.45,
    'allow_negative': True,
    'negative_tolerance_years': 2,
    'wacc_benchmark': 10.0,
    'roiic_veto_weighted_threshold': -5.0,
    'roiic_veto_latest_threshold': -3.0,
    'roiic_negative_penalty_buffer': 0.0,
    'roiic_negative_penalty_scale': 8.0,
    'roiic_negative_penalty_cap': 12.0,
    'roiic_divergence_slope_gap': 0.12,
    'roiic_positive_bonus_threshold': 12.0,
    'penalty_factor': 20,
    'max_penalty': 15,
    'severe_single_year_decline_pct': -35.0,
    'severe_single_year_penalty': 12,
    'relative_decline_ratio_70': 0.70,
    'relative_decline_penalty_70': 10,
    'relative_decline_ratio_60': 0.60,
    'relative_decline_penalty_60': 15,
    'sustained_decline_threshold': -0.18,
    'sustained_decline_penalty': 10,
}


def get_roiic_filter_config(industry: str) -> Dict[str, float]:
    """获取 ROIIC 专用的行业过滤配置。"""

    return ROIIC_INDUSTRY_FILTER_CONFIGS.get(
        industry,
        DEFAULT_ROIIC_FILTER_CONFIG.copy(),
    )


__all__ = [
    'ROIIC_INDUSTRY_FILTER_CONFIGS',
    'DEFAULT_ROIIC_FILTER_CONFIG',
    'get_roiic_filter_config',
]
